#!/bin/python3

import math
import os
import random
import re
import sys



#
# Complete the 'collectionfunc' function below.
#
# The function accepts following parameters:
#  1. STRING text1
#  2. DICTIONARY dictionary1
#  3. LIST key1
#  4. LIST val1
#  5. DICTIONARY deduct
#  6. LIST list1
#
import collections 
from collections import Counter 
def collectionfunc(text1, dictionary1, key1, val1, deduct, list1):
    # Write your code here  
    
    x = Counter(text1.split()) 
  
    # od = sorted(x,key = lambda x:x.keys())
    # print(od)
    y  =  dict(sorted(x.items(), key=lambda pair: pair[0]))  
    c = Counter(dictionary1) 
    print(y)
    c.subtract(deduct) 
    print(dict(c))  

    x = dict(zip(key1,val1))
    x.pop(key1[1])  
    x.update({key1[1]:val1[1]})
    print(x) 
    x = lambda x:x%2==0 
    even_nums = list(filter(lambda x: x%2 == 0, list1)) 
    odd_nums = list(filter(lambda x : x %2 != 0 ,list1)) 
    if len(even_nums) <= 0 :  
        c = {"odd":odd_nums} 
    elif len(odd_nums)<= 0 :
               c = {"even":even_nums}  
    elif len(odd_nums)<= 0 and len(even_nums) <= 0 :
        c = {}
    else : c = {"odd":odd_nums,"even":even_nums}  
    
    print(c)
      
if __name__ == '__main__':
    from collections import Counter

    text1 = input()
    
    n1 = int(input().strip())
    qw1 = []
    qw2 = []
    for _ in range(n1):
        qw1_item = (input().strip())
        qw1.append(qw1_item)
        qw2_item = int(input().strip())
        qw2.append(qw2_item)
    testdict={}
    for i in range(n1):
        testdict[qw1[i]]=qw2[i]
    collection1 = (testdict)
    
    qw1 = []
    n2 = int(input().strip())
    for _ in range(n2):
        qw1_item = (input().strip())
        qw1.append(qw1_item)
    key1 = qw1
    
    qw1 = []
    n3 = int(input().strip())
    for _ in range(n3):
        qw1_item = int(input().strip())
        qw1.append(qw1_item)
    val1 = qw1

    n4 = int(input().strip())
    qw1 = []
    qw2 = []
    for _ in range(n4):
        qw1_item = (input().strip())
        qw1.append(qw1_item)
        qw2_item = int(input().strip())
        qw2.append(qw2_item)
    testdict={}
    for i in range(n4):
        testdict[qw1[i]]=qw2[i]
    deduct = testdict

    qw1 = []
    n5 = int(input().strip())
    for _ in range(n5):
        qw1_item = int(input().strip())
        qw1.append(qw1_item)
    list1 = qw1

    collectionfunc(text1, collection1, key1, val1, deduct, list1)
--------------------------------------------------------------------------input --------------------------------------------------- 


how many times does each word show up in this sentence word times each each word
4
1
3
2
4
12
2
14
6
3
a
b
c
3
1
2
3
2
1
0
14
2
6
1
3
5
7
9
10
Your Output (stdout)
{'does': 1, 'each': 3, 'how': 1, 'in': 1, 'many': 1, 'sentence': 1, 'show': 1, 'this': 1, 'times': 2, 'up': 1, 'word': 3}
{'1': 3, '2': 4, '12': 2, '14': 4}
{'a': 1, 'c': 3, 'b': 2}
{'odd': [1, 3, 5, 7, 9], 'even': [10]}
Expected Output

Download
{'does': 1, 'each': 3, 'how': 1, 'in': 1, 'many': 1, 'sentence': 1, 'show': 1, 'this': 1, 'times': 2, 'up': 1, 'word': 3}
{'1': 3, '2': 4, '12': 2, '14': 4}
{'a': 1, 'c': 3, 'b': 2}
{'odd': [1, 3, 5, 7, 9], 'even': [10]}
