#!/bin/python3

import sys
import os
import datetime as dt


def log(func) :
    def inner(*args,**kwargs) :
         str_temp = "Accessed the function -'{}' with arguments {} {}".format(func.__name__,args,kwargs)
        
         return str_temp
#Add log function and inner function implementation here
    return inner  

@log
def greet(msg):
    'Greeting Message : ' + msg
    

greet("hello world!")
'''Check the Tail section for input/output'''
if __name__ == "__main__":
    with open(os.environ['OUTPUT_PATH'], 'w') as fout:
        res_lst = list()
        res_lst.append(greet(str(input())))
        fout.write("{}".format(*res_lst))
=============================================================2======================================================== 
def log(func):
    def inner(*args, **kwdargs):
        str_template = "Accessed the function -'{}' with arguments {} {}".format(func.__name__,
                                                                                args,
                                                                                kwdargs)
        return str_template + "\n" + str(func(*args, **kwdargs))
    return inner

#Add greet function definition here
@log 
def average(n1,n2,n3) :
    return (n1+n2+n3)/3

    
average(3,8,16) 

==============================3=========================================================================================
import sys
import os

#Define and implement bold_tag 
def bold_tag(func) :
    def inner(*args,**kwargs) :
        return '<b>' + func(*args,*kwargs)+"</b>"
    return inner

@bold_tag
def say(msg):
    return msg
     
say("Decorator exercise") 

==============4============================================================================================


import os
import sys

def bold_tag(func):
    
    def inner(*args, **kwdargs):
        return '<b>'+func(*args, **kwdargs)+'</b>'
        
    return inner

def italic_tag(func):
    
    def inner(*args, **kwdargs):
        return '<i>'+func(*args, **kwdargs)+'</i>'
        
    return inner
#Implement italic_tag below

@italic_tag
def say(msg):
    return msg
    
    
=======5==============================================================================================



import os
import sys
def bold_tag(func):
    
    def inner(*args, **kwdargs):
        return '<b>'+func(*args, **kwdargs)+'</b>'
        
    return inner

def italic_tag(func):
    
    def inner(*args, **kwargs):
        return '<i>'+func(*args, **kwargs)+'</i>'
        
    return inner
    
#Add greet() function definition 
@italic_tag
def greet() :
    return input() 
    
    
    
    
    
  ===========================================================6============================================================
  
  
  import os
import sys

def bold_tag(func):
    
    def inner(*args, **kwdargs):
        return '<b>'+func(*args, **kwdargs)+'</b>'
        
    return inner

def italic_tag(func):
    
    def inner(*args, **kwdargs):
        return '<i>'+func(*args, **kwdargs)+'</i>'
        
    return inner
    
#Add greet() implementation here 
@italic_tag
@bold_tag 
 
def greet() : 
    return input()
